### ISSUE TITLE
Unsafe usage of transfer()

### ISSUE THREAD

**Issue by kryptoklob** [GarryPlays/Chibi_Public#1]
In ChibiBattles.sol, and likely other areas, the `transfer()` function is used to send winnings to the winning team.

This is unsafe, because a separate smart contract could interact with the system and reject() or otherwise DOS the battle, leaving it in an ever-pending state that could not be finished.

Possible solution: prevent smart contracts from playing by checking that `msg.sender == tx.origin` on all public transaction calls.

**Comment by GarryPlays** [comment]
Thank you for pointing this out. We do not see a thread here.
Vitalik himself is against the tx.origin. These functions can only be called by us or a designated 3rd party whose access we can cancel if foul play is at hand.
